version: '3'

services:
    graphql-server:
        image: node:latest
        volumes:
            - ./graphql-server:/usr/src/graphql-server
        environment:
            - NODE_ENV=development
        network_mode: host
        working_dir: /usr/src/graphql-server
        command: bash -c "npm install && npm start"
        ports:
            - 5000:5000
    api:
        image: node:latest
        volumes:
            - ./api:/usr/src/api
        environment:
            - NODE_ENV=development
        network_mode: host
        working_dir: /usr/src/api
        command: bash -c "npm install && npm run dev"
        ports:
            - 4000:4000
    client:
        image: node:latest
        volumes:
            - ./clientv2:/usr/src/client
        environment:
            - NODE_ENV=development
        network_mode: host
        working_dir: /usr/src/client
        command: bash -c "npm install && npm start"
        ports:
            - 3000:3000
    api-kafka:
        image: node:latest
        volumes:
            - ./api-kafka:/usr/src/api-kafka
        environment:
            - NODE_ENV=development
        network_mode: host
        working_dir: /usr/src/api-kafka
        command: bash -c "npm install && npm run dev"
        ports:
            - 6000:6000

